# Generated by Django 6.0.2 on 2026-03-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='appointment_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='appointment_format',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('virtual', 'Virtual')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('solar', 'Solar'), ('hvac', 'HVAC')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='homeowner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
