# Generated by Django 6.0.2 on 2026-03-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_lead_appointment_datetime_lead_appointment_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('home_address', models.CharField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, choices=[('solar', 'Solar'), ('hvac', 'HVAC'), ('both', 'Both')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('solar', 'Solar'), ('hvac', 'HVAC'), ('both', 'Both')], max_length=10),
        ),
    ]
