# Generated by Django 6.0.2 on 2026-03-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_rep_alter_lead_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
