# Generated by Django 6.0.2 on 2026-03-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_rep_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='color',
            field=models.CharField(default='#2980b9', max_length=7),
        ),
    ]
