# Generated by Django 6.0.2 on 2026-03-04 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_rep_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='maps.rep'),
        ),
    ]
