# Generated by Django 6.0.2 on 2026-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_lead_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
