# Generated by Django 6.0.2 on 2026-03-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_lead_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='disposition',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('no_sale', 'No Sale'), ('follow_up', 'Follow Up'), ('credit_fail', 'Credit Fail'), ('cancel_door', 'Cancel at Door'), ('cpfu', 'CPFU'), ('rep_no_show', 'Rep No Show'), ('no_coverage', 'No Coverage')], max_length=20),
        ),
    ]
