# Generated by Django 6.0.2 on 2026-03-11 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=20)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=64)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='maps.rep')),
            ],
        ),
    ]
