# Generated by Django 6.0.2 on 2026-03-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_alter_lead_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='call_transcript',
            field=models.TextField(blank=True),
        ),
    ]
