# Generated by Django 6.0.2 on 2026-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_lead_follow_up_date_alter_lead_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
