# Generated by Django 6.0.2 on 2026-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_lead_sat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
