# Generated by Django 6.0.2 on 2026-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_lead_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['appointment_datetime'], name='maps_lead_appoint_6edd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['rep'], name='maps_lead_rep_id_f6b0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['disposition'], name='maps_lead_disposi_9ab6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['rep', 'date', 'status'], name='maps_timeof_rep_id_348568_idx'),
        ),
    ]
