# Generated by Django 6.0.2 on 2026-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_lead_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='disposition',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('no_sale', 'No Sale'), ('follow_up', 'Follow Up'), ('credit_fail', 'Credit Fail'), ('cancel_door', 'Cancel at Door'), ('cpfu', 'CPFU'), ('rep_no_show', 'Rep No Show'), ('no_coverage', 'No Coverage'), ('needs_reschedule', 'Needs Reschedule'), ('incomplete_deal', 'Incomplete Deal'), ('future_contact', 'Future Contact'), ('dq', 'DQ')], max_length=20),
        ),
    ]
