# Generated by Django 6.0.2 on 2026-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_leadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
