# Generated by Django 6.0.2 on 2026-04-30 23:36

from django.db import migrations, models


def backfill_end_date(apps, schema_editor):
    TimeOffRequest = apps.get_model('maps', 'TimeOffRequest')
    TimeOffRequest.objects.filter(end_date__isnull=True).update(end_date=models.F('start_date'))


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_add_source_and_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_end_date, migrations.RunPython.noop),
    ]
