# Generated by Django 6.0.2 on 2026-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_time_off_date_ranges'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepCountDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lead_sources',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('rep', 'Rep'), ('provider', 'Provider')], default='rep', max_length=10),
        ),
        migrations.CreateModel(
            name='RepCountOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_block', models.CharField(choices=[('morning', '9-11 AM'), ('midday', '12-2 PM'), ('afternoon', '3-5 PM'), ('evening', '6-8 PM')], max_length=10)),
                ('count', models.IntegerField()),
            ],
            options={
                'unique_together': {('date', 'time_block')},
            },
        ),
    ]
