# Generated by Django 6.0.2 on 2026-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_repcountdefault_userprofile_lead_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repcountdefault',
            name='time_block',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='repcountoverride',
            name='time_block',
            field=models.CharField(choices=[('morning', '9-12 PM'), ('midday', '12-3 PM'), ('afternoon', '3-6 PM'), ('evening', '6-9 PM')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='repcountdefault',
            unique_together={('time_block',)},
        ),
    ]
