# Generated by Django 6.0.2 on 2026-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_rep_count_default_per_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
