# Generated by Django 6.0.2 on 2026-05-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0026_add_lead_cancelled_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hourly_availability',
            field=models.BooleanField(default=False),
        ),
    ]
