# Generated by Django 6.0.2 on 2026-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_add_hourly_availability_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='appt_notes',
            field=models.TextField(blank=True),
        ),
    ]
