# Generated by Django 6.0.2 on 2026-06-10 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0031_apitenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(choices=[('disposition', 'Disposition'), ('appointment', 'Appointment'), ('test', 'Test')], max_length=20)),
                ('lead_name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('payload', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
