# Generated by Django 6.0.2 on 2026-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0033_tenant_theming'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='sms_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rep',
            name='sms_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
