# Generated by Django 6.0.2 on 2026-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0036_webhook_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('disposition_changed', 'Disposition Changed'), ('appointment_changed', 'Appointment DateTime Changed'), ('lead_created', 'New Lead Created'), ('lead_cancelled', 'Lead Cancelled'), ('rep_assigned', 'Rep Assigned'), ('sat_changed', 'SAT Changed'), ('follow_up_set', 'Follow-Up Date Set')], max_length=30)),
                ('url', models.URLField(max_length=1000)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', max_length=6)),
                ('fields', models.JSONField(default=list)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
