# Generated by Django 6.0.2 on 2026-08-03 17:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0038_seed_webhook_configs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_inbound', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='leadmessage',
            options={'base_manager_name': 'all_objects', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='leadupdate',
            options={'base_manager_name': 'all_objects', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='rep',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='repcountdefault',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='repcountoverride',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='timeoffrequest',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='voicecalllog',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='lead',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='leadmessage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='leadupdate',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='manager',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rep',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='repcountdefault',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='repcountoverride',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timeoffrequest',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='voicecalllog',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='repcountdefault',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='repcountoverride',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='apitenant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_tenants', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='ghlwebhooklog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='leadmessage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='leadupdate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='manager',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='rep',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='repcountdefault',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='repcountoverride',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='voicecalllog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='maps.organization'),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_configs', to='maps.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='repcountdefault',
            unique_together={('organization', 'time_block')},
        ),
        migrations.AlterUniqueTogether(
            name='repcountoverride',
            unique_together={('organization', 'date', 'time_block')},
        ),
        migrations.CreateModel(
            name='OrgSwitchAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maps.organization')),
                ('to_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maps.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_switches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
