# Generated by Django 6.0.2 on 2026-09-18 19:01
#
# The one schema change the Wednesday hub needs (INTEGRATION.md §4):
#
# - Lead.hub_customer_id — nullable, indexed, not unique.
# - Lead.updated_at — existing rows are backfilled to the time this migration
#   runs. That over-reports (every lead looks changed once) but never
#   under-reports, which is the safe direction for a change feed.
# - Lead.updated_at is maintained by a PostgreSQL trigger, because auto_now
#   only fires on a full save(): queryset .update() (Alfred's disposition
#   write, bulk edit, route confirm/clear) and save(update_fields=[...]) (GHL
#   cancel/disposition, TextBlast claim, auto-assign) skip it. The trigger
#   also fills updated_at on INSERT, so code that predates this migration can
#   still create leads if the deploy is rolled back without reversing it.
# - WebhookConfig.trigger gains 'appt_rescheduled' (choices only; no SQL).
#
# SQLite (local dev) gets the columns but no trigger; there auto_now still
# covers save().

from django.db import migrations, models

# Stamps the reminder worker and TextBlast write for their own bookkeeping.
# Changing only these does not bump updated_at, so the hub is not sent
# re-polling leads whose customer-visible state did not change.
IGNORED_COLUMNS = (
    'updated_at',
    'dispo_reminder_sent_at',
    'dispo_call_made_at',
    'follow_up_reminder_sent_at',
    'textblast_sent_at',
)

CREATE_FUNCTION = """
CREATE OR REPLACE FUNCTION maps_lead_set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $fn$
DECLARE
    ignored CONSTANT text[] := ARRAY[{ignored}];
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF (to_jsonb(NEW) - ignored) IS NOT DISTINCT FROM (to_jsonb(OLD) - ignored) THEN
            -- Nothing a hub mirrors changed (a no-op save, or a stamp-only
            -- write). Keep the old value; this also means updated_at cannot
            -- be set by hand.
            NEW.updated_at := OLD.updated_at;
            RETURN NEW;
        END IF;
    END IF;
    -- clock_timestamp(), not now(): now() is the transaction's start time,
    -- which lands further before the commit and so widens the window in
    -- which a poller can advance past a row it cannot see yet.
    NEW.updated_at := clock_timestamp();
    RETURN NEW;
END;
$fn$;
""".format(ignored=', '.join(f"'{c}'" for c in IGNORED_COLUMNS))

CREATE_TRIGGER = """
CREATE TRIGGER maps_lead_updated_at
    BEFORE INSERT OR UPDATE ON maps_lead
    FOR EACH ROW EXECUTE FUNCTION maps_lead_set_updated_at();
"""


def install_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(CREATE_FUNCTION)
    schema_editor.execute(CREATE_TRIGGER)


def remove_trigger(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute('DROP TRIGGER IF EXISTS maps_lead_updated_at ON maps_lead;')
    schema_editor.execute('DROP FUNCTION IF EXISTS maps_lead_set_updated_at();')


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0041_copy_reps_to_ventana'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hub_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='trigger',
            field=models.CharField(choices=[('disposition_changed', 'Disposition Changed'), ('appointment_changed', 'Appointment DateTime Changed'), ('lead_created', 'New Lead Created'), ('lead_cancelled', 'Lead Cancelled'), ('rep_assigned', 'Rep Assigned'), ('sat_changed', 'SAT Changed'), ('follow_up_set', 'Follow-Up Date Set'), ('appt_rescheduled', 'Appointment Rescheduled by GHL')], max_length=30),
        ),
        migrations.RunPython(install_trigger, remove_trigger),
    ]
