"""
Django settings for dispo project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The insecure fallback only exists so the site stays up if the env var is
# missing — set SECRET_KEY on Railway (rotating it logs every user out).
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-rynul5+8h@3^(3@)is*rn#32u*b9cpnw)g%y3_b-$e^n-e@%*!',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False; set DEBUG=True in local .env for development.
DEBUG = os.environ.get('DEBUG', 'False').strip().lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get(
    'ALLOWED_HOSTS',
    'sutton-soda.com,www.sutton-soda.com,'
    'lavish-reflection-production-1e5f.up.railway.app,'
    'healthcheck.railway.app,localhost,127.0.0.1',
).split(',') if h.strip()]
# Railway injects its public domain — keep it valid even if the domain changes.
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
if _railway_domain and _railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)

# Railway terminates TLS at its proxy and forwards plain HTTP with this header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'maps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'maps.middleware.OrganizationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dispo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'maps.context_processors.user_role',
                'maps.context_processors.organization',
            ],
        },
    },
]

WSGI_APPLICATION = 'dispo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Twilio
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
# Toll-free 833 line — Alfred's voice number. Carrier-filtered for SMS, so it
# is no longer used as an SMS From number (voice calls only).
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')
# 978 local number with approved A2P registration.
TWILIO_PHONE_NUMBER_2 = os.environ.get('TWILIO_PHONE_NUMBER_2', '')
# All outbound SMS sends From this number. Falls back to the 833 line only if
# the 978 env var is missing, so sends never silently stop.
TWILIO_SMS_FROM_NUMBER = (
    os.environ.get('TWILIO_SMS_FROM_NUMBER', '')
    or TWILIO_PHONE_NUMBER_2
    or TWILIO_PHONE_NUMBER
)

# OpenAI
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.dev', 'https://*.up.railway.app', 'https://sutton-soda.com', 'https://www.sutton-soda.com']

# CORS — v1 API endpoints only, origins controlled per-tenant
CORS_ALLOW_ALL_ORIGINS = False
CORS_URLS_REGEX = r'^/api/v1/.*$'
CORS_ALLOW_HEADERS = ['authorization', 'content-type', 'accept']
CORS_ALLOWED_ORIGIN_REGEXES = [r'.*']

# Auth
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Sessions — stay logged in for 1 week
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
SESSION_SAVE_EVERY_REQUEST = True

# With DEBUG off, Django's default logging drops app-level warnings — send
# everything WARNING+ to the console so Twilio signature failures
# (TWILIO_SIG_FAIL) and worker errors show up in Railway logs.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
}
